"""add user profiles

Revision ID: 005a39aa16a9
Revises: 7c054d70b2b4
Create Date: 2024-04-11 11:07:46.982559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005a39aa16a9'
down_revision = '7c054d70b2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
