"""added add_info column to fish model

Revision ID: d4bfce5b0f89
Revises: 005a39aa16a9
Create Date: 2024-05-24 15:09:09.672802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bfce5b0f89'
down_revision = '005a39aa16a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_info', sa.String(length=4000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishes', schema=None) as batch_op:
        batch_op.drop_column('add_info')

    # ### end Alembic commands ###
